# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Python\MCSL\dev\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 469)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Code\\Python\\MCSL\\dev\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("D:\\Code\\Python\\MCSL\\dev\\icon.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(620, 330, 100, 100))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_pushButton.setObjectName("start_pushButton")
        self.exit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exit_pushButton.setGeometry(QtCore.QRect(620, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.exit_pushButton.setFont(font)
        self.exit_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.set_java_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.set_java_lineEdit.setGeometry(QtCore.QRect(30, 60, 381, 31))
        self.set_java_lineEdit.setStyleSheet("")
        self.set_java_lineEdit.setObjectName("set_java_lineEdit")
        self.set_java_label = QtWidgets.QLabel(self.centralwidget)
        self.set_java_label.setGeometry(QtCore.QRect(30, 40, 381, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.set_java_label.setFont(font)
        self.set_java_label.setTextFormat(QtCore.Qt.PlainText)
        self.set_java_label.setObjectName("set_java_label")
        self.set_java_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.set_java_pushButton.setGeometry(QtCore.QRect(420, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.set_java_pushButton.setFont(font)
        self.set_java_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.set_java_pushButton.setObjectName("set_java_pushButton")
        self.set_java_ok_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.set_java_ok_pushButton.setGeometry(QtCore.QRect(540, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.set_java_ok_pushButton.setFont(font)
        self.set_java_ok_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.set_java_ok_pushButton.setObjectName("set_java_ok_pushButton")
        self.auto_find_java_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.auto_find_java_pushButton.setGeometry(QtCore.QRect(480, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.auto_find_java_pushButton.setFont(font)
        self.auto_find_java_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.auto_find_java_pushButton.setObjectName("auto_find_java_pushButton")
        self.download_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.download_toolButton.setGeometry(QtCore.QRect(620, 220, 101, 101))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(17)
        self.download_toolButton.setFont(font)
        self.download_toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_toolButton.setObjectName("download_toolButton")
        self.set_core_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.set_core_pushButton.setGeometry(QtCore.QRect(30, 130, 251, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.set_core_pushButton.setFont(font)
        self.set_core_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.set_core_pushButton.setObjectName("set_core_pushButton")
        self.copy_core_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.copy_core_pushButton.setGeometry(QtCore.QRect(320, 130, 241, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.copy_core_pushButton.setFont(font)
        self.copy_core_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy_core_pushButton.setObjectName("copy_core_pushButton")
        self.set_core_label = QtWidgets.QLabel(self.centralwidget)
        self.set_core_label.setGeometry(QtCore.QRect(30, 110, 561, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.set_core_label.setFont(font)
        self.set_core_label.setTextFormat(QtCore.Qt.PlainText)
        self.set_core_label.setObjectName("set_core_label")
        self.min_mem_label = QtWidgets.QLabel(self.centralwidget)
        self.min_mem_label.setGeometry(QtCore.QRect(29, 180, 241, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.min_mem_label.setFont(font)
        self.min_mem_label.setTextFormat(QtCore.Qt.PlainText)
        self.min_mem_label.setObjectName("min_mem_label")
        self.max_mem_label = QtWidgets.QLabel(self.centralwidget)
        self.max_mem_label.setGeometry(QtCore.QRect(290, 180, 361, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.max_mem_label.setFont(font)
        self.max_mem_label.setTextFormat(QtCore.Qt.PlainText)
        self.max_mem_label.setObjectName("max_mem_label")
        self.min_mem_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.min_mem_spinBox.setGeometry(QtCore.QRect(100, 180, 91, 22))
        self.min_mem_spinBox.setObjectName("min_mem_spinBox")
        self.max_mem_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.max_mem_spinBox.setGeometry(QtCore.QRect(360, 180, 91, 22))
        self.max_mem_spinBox.setObjectName("max_mem_spinBox")
        self.mem_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.mem_pushButton.setGeometry(QtCore.QRect(500, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.mem_pushButton.setFont(font)
        self.mem_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mem_pushButton.setObjectName("mem_pushButton")
        self.introduction_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.introduction_textBrowser.setGeometry(QtCore.QRect(20, 220, 541, 211))
        self.introduction_textBrowser.setObjectName("introduction_textBrowser")
        self.export_config_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.export_config_toolButton.setGeometry(QtCore.QRect(620, 170, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.export_config_toolButton.setFont(font)
        self.export_config_toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_config_toolButton.setObjectName("export_config_toolButton")
        self.import_config_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.import_config_toolButton.setGeometry(QtCore.QRect(620, 120, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.import_config_toolButton.setFont(font)
        self.import_config_toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.import_config_toolButton.setObjectName("import_config_toolButton")
        self.check_update_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.check_update_pushButton.setGeometry(QtCore.QRect(620, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.check_update_pushButton.setFont(font)
        self.check_update_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_update_pushButton.setObjectName("check_update_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCSL v1.3"))
        self.start_pushButton.setText(_translate("MainWindow", "启动"))
        self.exit_pushButton.setText(_translate("MainWindow", "退出程序"))
        self.set_java_label.setText(_translate("MainWindow", "设置Java路径：（切勿包含中文和特殊字符）"))
        self.set_java_pushButton.setText(_translate("MainWindow", "选择"))
        self.set_java_ok_pushButton.setText(_translate("MainWindow", "确定"))
        self.auto_find_java_pushButton.setText(_translate("MainWindow", "查找"))
        self.download_toolButton.setText(_translate("MainWindow", "下载"))
        self.set_core_pushButton.setText(_translate("MainWindow", "选择..."))
        self.copy_core_pushButton.setText(_translate("MainWindow", "确定"))
        self.set_core_label.setText(_translate("MainWindow", "选择服务器核心：（一个服务器仅须操作一次,选过就不需要再操作）"))
        self.min_mem_label.setText(_translate("MainWindow", "最小内存:              MB"))
        self.max_mem_label.setText(_translate("MainWindow", "最大内存:              MB"))
        self.mem_pushButton.setText(_translate("MainWindow", "确定"))
        self.introduction_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">MCSL v1.3  ——Made by LxHTT and ChinaT</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">这是由两个人制作的MC服务器启动器。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">软件包含了下载、设参、启动诸多功能。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Java默认下载AdoptOpenJDK，其余可以自行百度。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体,monospace\'; font-size:12pt; font-weight:600; color:#ff0000;\">服务器核心已经支持了</span><span style=\" font-family:\'JetBrains Mono,monospace\'; font-size:12pt; font-weight:600; color:#ff0000;\">Paper</span><span style=\" font-family:\'宋体,monospace\'; font-size:12pt; font-weight:600; color:#ff0000;\">和</span><span style=\" font-family:\'JetBrains Mono,monospace\'; font-size:12pt; font-weight:600; color:#ff0000;\">Spigot</span><span style=\" font-family:\'宋体,monospace\'; font-size:12pt; font-weight:600; color:#ff0000;\">下载。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">服务器路径为程序同目录下的</span><span style=\" font-size:12pt; font-weight:600;\">server</span><span style=\" font-size:12pt;\">文件夹。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">如果无法启动，可使用程序在server文件夹生成的备用启动方式</span><span style=\" font-size:12pt; font-weight:600;\">command.bat</span><span style=\" font-size:12pt;\">。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">由于暂时不会考虑添加关闭服务器功能，所以如需关闭服务器，请在服务器中输入</span><span style=\" font-size:12pt; font-weight:600; color:#c80b37;\">stop</span><span style=\" font-size:12pt;\">指令来安全关闭您的服务器。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">遇到Bug，请积极反馈。反馈地址：</span><span style=\" font-family:\'JetBrains Mono,monospace\'; font-size:9.8pt; color:#bd93f9;\">https://www.wjx.top/vm/mBwRt23.aspx</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">主程序</span><span style=\" font-size:12pt; color:#00aa00;\">&amp;</span><span style=\" font-size:12pt;\">自动查找Java算法：落雪无痕LxHTT   QQ：3395314362</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">下载模块</span><span style=\" font-size:12pt; color:#00aa00;\">&amp;</span><span style=\" font-size:12pt;\">自动查找Java的UI：ChinaT   QQ：3273789867</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">——————————————————————</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">v1.3更新日志：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">优化代码逻辑和UI，减小程序目录臃肿程度。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">添加检查更新功能，为MCSL 2铺路。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">MCSL 2使用C#开发，更加强大！</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">v1.2更新日志：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">整合各个下载程序，集成而强大。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">美化UI！！！！！！</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">优化代码的逻辑性以及可读性（原先自己都傻了）</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">———————————</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">v1.1更新日志：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">修复在未选择Jar情况下闪退的Bug</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">增加了配置导入导出功能。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">增加了许多温馨提示（</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">程序启动默认读取目录下的config.mcsl.ini配置文件。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">优化了各下载模块的UI。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">增加自动查找Java功能。（算法由LxHTT编写，UI由ChinaT制作）</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">———————————</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">v1.0更新日志：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">初版。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Java自动查找功能暂时不可用，可自行设定路径。</span></p></body></html>"))
        self.export_config_toolButton.setText(_translate("MainWindow", "导出配置"))
        self.import_config_toolButton.setText(_translate("MainWindow", "导入配置"))
        self.check_update_pushButton.setText(_translate("MainWindow", "检查更新"))
