# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_java.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class downJava(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(375, 194)
        font = QtGui.QFont()
        font.setPointSize(1)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(100, 70, 201, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(154, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "下载Java"))
        self.label.setText(_translate("Dialog", "Tips：下载的是AdoptOpenJDK，下载后解压即可"))
        self.comboBox.setItemText(0, _translate("Dialog", "——————请选择——————"))
        self.comboBox.setItemText(1, _translate("Dialog", "Java 8（1.0-1.16.x）"))
        self.comboBox.setItemText(2, _translate("Dialog", "Java 16（1.17.x)"))
        self.comboBox.setItemText(3, _translate("Dialog", "Java 17（1.17.x-1.18.x）"))
        self.comboBox.setItemText(4, _translate("Dialog", "Java 18（1.19+）"))
        self.pushButton.setText(_translate("Dialog", "选择保存位置&&下载"))
        self.label_2.setText(_translate("Dialog", "选择版本："))
